// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO-e_emO5qqPQiwoNfXya7p4PV59dGaJA',
    appId: '1:228475727893:web:7d9f20250cb66a96985e1c',
    messagingSenderId: '228475727893',
    projectId: 'ppdb-app-45bc8',
    authDomain: 'ppdb-app-45bc8.firebaseapp.com',
    storageBucket: 'ppdb-app-45bc8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANXClrH0kZMjut2uKMEVbPamluZ-UhdRc',
    appId: '1:228475727893:android:55311dee9d585b50985e1c',
    messagingSenderId: '228475727893',
    projectId: 'ppdb-app-45bc8',
    storageBucket: 'ppdb-app-45bc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvFVyO9skAG0XGzu3__WBGrWrifvg2V5k',
    appId: '1:228475727893:ios:0efb7e7bd13cf243985e1c',
    messagingSenderId: '228475727893',
    projectId: 'ppdb-app-45bc8',
    storageBucket: 'ppdb-app-45bc8.firebasestorage.app',
    iosClientId: '228475727893-uq1l06ohg035kn9onakgfq8v2008r0b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ppdbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvFVyO9skAG0XGzu3__WBGrWrifvg2V5k',
    appId: '1:228475727893:ios:0efb7e7bd13cf243985e1c',
    messagingSenderId: '228475727893',
    projectId: 'ppdb-app-45bc8',
    storageBucket: 'ppdb-app-45bc8.firebasestorage.app',
    iosClientId: '228475727893-uq1l06ohg035kn9onakgfq8v2008r0b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ppdbApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO-e_emO5qqPQiwoNfXya7p4PV59dGaJA',
    appId: '1:228475727893:web:23dbc1101a363584985e1c',
    messagingSenderId: '228475727893',
    projectId: 'ppdb-app-45bc8',
    authDomain: 'ppdb-app-45bc8.firebaseapp.com',
    storageBucket: 'ppdb-app-45bc8.firebasestorage.app',
  );
}
